- name: install centos packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    # monitor utils
    - htop
    - iotop
    - iftop
    - nethogs
    - ncdu
    - glances
    # other useful stuff
    - mc
    - vim
    - tmux
    - bash-completion
    - less
    - rsync
    - file
    - psmisc
    - git
    # archive/compression tools
    - xz
    - bzip2
    - gzip
    - zip
    - unzip
    # various interpreters 
    - python
    - python34
    - python2-pip
    - python34-pip
  become: yes
