- name: install fedora packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    # monitor utils
    - htop
    - iotop
    - iftop
    - nethogs
    - ncdu
    - glances
    # other useful stuff
    - mc
    - vim
    - tmux
    - bash-completion
    - less
    - rsync
    - file
    - psmisc
    - git
    # archive/compression tools
    - xz
    - bzip2
    - gzip
    - zip
    - unzip
    # python & pip
    - python
    - python3
    - python-pip
    - python3-pip
  become: yes
