---
- name: configure apt sources
  template: src=templates/sources.list.j2 dest=/etc/apt/sources.list
  notify: update apt cache
  become: true

- name: configure apt proxy
  template: src=apt-proxy.j2 dest=/etc/apt/apt.conf.d/50proxy
  when: deb_apt_proxy is defined
  become: true
