---

- name: ensure ~/.local/share/fonts/ exists
  file: path=~/.local/share/fonts/ state=directory recurse=yes

- name: get powerline fonts
  git: repo=https://github.com/powerline/fonts.git dest=~/.local/share/fonts/powerline
  register: get_powerline_fonts
  when: "'powerline_fonts' in user.configure_items"

- name: get artwiz fonts
  git: repo=https://github.com/whitelynx/artwiz-fonts-wl dest=~/.local/share/fonts/artwiz
  register: get_artwiz_fonts
  when: "'artwiz_fonts' in user.configure_items"

- name: refresh fontcache
  shell: fc-cache
  when: get_powerline_fonts.changed or get_artwiz_fonts.changed
