- apt:
    update_cache: yes
    cache_valid_time: 3600
    state: present
    name: "{{ item }}"
  with_items:
    - lightdm
    - lightdm-gtk-greeter
  when: ansible_distribution == "Debian"

- dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - lightdm
    - lightdm-gtk
  when: ansible_distribution == "Fedora"
  notify: start lightdm
