---
- name: install i3 and related
  include: install.yml
  become: yes

- name: user specific configuration
  include: user.yml
  become: yes
  become_user: "{{ user.name }}"
  loop_control:
    loop_var: user
  with_items: "{{ users }}"
  when: "'i3' in user.configure_items"
